export const character = [
  "Nathan Drake",
  "Chloe Frazer",
  "Samuel Drake",
  "Elena Fisher",
  "Victor Sullivan",
  "Johnny Cage",
  "Kano",
  "Sonya Blade",
  "Noob Saibot",
  "Quan Chi",
  "Bo' Rai Cho",
  "Cassie Cage",
  "Erron Black",
  "Jacqui Briggs",
  "Kotal Kahn",
  "Kung Jin",
  "Takeda",
  "Triborg",
  "Kronika",
  "Reptile",
  "Sub Zero",
  "Scorpion",
  "Liu Kang",
  "Kung Lao",
  "Shao Kahn",
  "Mario",
  "Luigi",
  "Shang Tsung",
  "Tiger King",
  "Joseph Stalin",
  "Vladimir Putin",
];
