export const frases = [
  "Don't make me laugh!",
  "All too easy!",
  "You weak pathetic fool!",
  "That was pathetic!",
  "I won!",
  "I am Shao Kahn… Bow to me!",
  "Is That's your best?",
  "You suck!",
  "It's official - you suck!",
  "You will die!",
  "You are nothing!",
  "You will never win!",
  "Feel the Power of Shao Kahn!",
  "Feel the wrath of Shao Kahn!",
  "I will destroy you!",
  "I rule this world!",
  "You will die, mortal!",
  "Prepare to die!",
  "Let the carnage begin!",
  "Somebody help me?",
  "I am once again asking for you'r financial support.",
  "Dude, you're acting like Karen! Stop it!",
  "Somebody Put Something in My Drink.",
  "Treasure these moments as if they were your last.",
  "Look at him. No dignity, no manners. Yet in the realm of Earth, men like him can amass great wealth and almost godlike power.",
  "You disappoint me. Not very wise.",
  "Flawless victory. Your soul is mine.",
  "I see. You're very foolish. The true sign of a hero.",
  "Leave us. I will take care of this impudent mortal myself.",
  "I can see into your soul. You will die.",
  "Save your pity for the weak.",
  "From this moment on, my island will be your battleground.",
  "Is it time? -Yes. We've let these humans win enough.",
  "Finish him quickly. Pay me my tribute.",
  "Mortal Kombat continues. I'm simply changing the place... as we agreed.",
  "Your brother's soul is mine.",
  "You will be next.",
  "I have plans for my beautiful Sonya.",
  "This is no time for foolish pride.",
  "Let Mortal Kombat begin.",
  "You imbecile.",
  "You're mine.",
  "If you so much as touch her... you're going to need a Seeing Eye dog.",
  "Scorpion and Sub-Zero, deadliest of enemies. But slaves under my power.",
  "Why else would I have chosen such a disreputable-looking cretin? ",
  "The emperor will not tolerate failure. And neither will I.",
  "We are not alone.",
  "Challenging Goro, eh? You weren't supposed to fight him now. Are you that eager to die?",
  "Hoping against hope. Such an endearing human trait. I'm touched, really.",
  "Shang Tsung, at your service.",
  "Welcome. You're here to compete in Mortal Kombat.",
  "Some of you will even have the distinct honor and pleasure to face Prince Goro, our reigning champion.",
  "We've never been so close to absolute victory, which is why I've come to warn you of another danger.",
  "As you wish. As absurd as your request is, I shall grant it.",
  "It's Mario",
  "Get over here!",
  "I am never going to financially recover from this.",
];
